"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { formatCents,formatDate,requestJson } from "@/lib/operational";
type Row={id:string;status?:string;created_at?:string;submitted_at?:string;connected_at?:string;amount_cents?:number;gross_amount_cents?:number;legal_name?:string;holder_name?:string;full_name?:string;email?:string;external_account_id?:string;action?:string};
export function AdminView({identity,pix,withdrawals,payments,webhooks,connections,users,audit}:{identity:Row[];pix:Row[];withdrawals:Row[];payments:Row[];webhooks:Row[];connections:Row[];users:Row[];audit:Row[]}){
 const router=useRouter(),[tab,setTab]=useState("Identidade"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const groups:Record<string,Row[]>={Identidade:identity,"Chaves Pix":pix,Saques:withdrawals,Pagamentos:payments,Webhooks:webhooks,Conexões:connections,Usuários:users,Auditoria:audit};
 async function act(path:string,status:string){if(!confirm(`Confirmar a alteração para ${status}?`))return;const reference=status==="paid"?prompt("Informe o identificador do comprovante do Pix:"):undefined;const reviewNote=status==="approved"?prompt("Informe a referência da verificação externa de identidade:"):undefined;if(status==="paid"&&!reference||status==="approved"&&!reviewNote)return;setBusy(true);setError("");try{await requestJson(path,{method:"PATCH",body:JSON.stringify({status,receiptReference:reference,reviewNote})});router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao atualizar.");}finally{setBusy(false);}}
 return <><PageHeader title="Admin Prosperity" description="Revisão financeira e operações da plataforma."/><nav className="detail-tabs">{Object.keys(groups).map(name=><button key={name} onClick={()=>setTab(name)} className={tab===name?"active":""}>{name}</button>)}</nav>{error&&<p className="form-error" role="alert">{error}</p>}<section className="panel operational-panel"><h2>{tab}</h2>{groups[tab].length?groups[tab].map(row=><div className="record-row" key={row.id}><strong>{row.legal_name??row.holder_name??row.full_name??row.external_account_id??row.action??row.email??row.id.slice(0,8)}</strong><span>{row.status??""} · {row.amount_cents!=null?formatCents(row.amount_cents):row.gross_amount_cents!=null?formatCents(row.gross_amount_cents):""} · {formatDate(row.created_at??row.submitted_at??row.connected_at)}</span><span className="button-row">{tab==="Identidade"&&row.status==="under_review"&&["approved","rejected"].map(s=><button disabled={busy} className="secondary-button" key={s} onClick={()=>act(`/api/admin/identity-verifications/${row.id}`,s)}>{s}</button>)}{tab==="Chaves Pix"&&row.status==="pending"&&["verified","rejected"].map(s=><button disabled={busy} className="secondary-button" key={s} onClick={()=>act(`/api/admin/payout-accounts/${row.id}`,s)}>{s}</button>)}{tab==="Saques"&&["requested","processing"].includes(row.status??"")&&[...(row.status==="requested"?["processing","rejected"]:["paid","failed"])].map(s=><button disabled={busy} className="secondary-button" key={s} onClick={()=>act(`/api/admin/withdrawals/${row.id}`,s)}>{s}</button>)}</span></div>):<p>Nenhum registro nesta área.</p>}</section></>;
}
