"use client";
import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { formatCents, formatDate } from "@/lib/operational";
import { mercadoPagoPaymentMetadata } from "@/lib/payments/mercado-pago-payment-metadata";
type Order = { id:string; product_id:string; offer_id:string; status:string; settlement_model:string; products:{name:string}|null; offers:{name:string}|null; customers:{name:string|null;email:string}|null; financial_snapshots:{prosperity_fee_amount_cents:number;affiliate_amount_cents:number;coproducer_amount_cents:number;producer_amount_cents:number}|null };
type Payment = { id:string; order_id:string; status:string; external_payment_id:string|null; external_reference:string; gross_amount_cents:number; provider_fee_amount_cents:number; created_at:string; raw_provider_data:unknown; payment_transactions:{transaction_type:string;status:string|null;occurred_at:string|null;created_at:string}[] };
function methodOf(payment:Payment) { const method=mercadoPagoPaymentMetadata(payment.raw_provider_data).method; return method==="pix"?"PIX":method==="card"?"Cartão":"—"; }
export function PaymentsView({ orders, payments }: { orders:Order[]; payments:Payment[] }) {
 const [selected,setSelected]=useState<string|null>(null),[period,setPeriod]=useState(""),[cutoff,setCutoff]=useState(0),[status,setStatus]=useState(""),[product,setProduct]=useState(""),[offer,setOffer]=useState(""),[method,setMethod]=useState(""),[model,setModel]=useState("");
 const orderMap=new Map(orders.map(o=>[o.id,o]));
 const chosen=payments.find(p=>p.id===selected), detail=chosen&&orderMap.get(chosen.order_id);
 const list=payments.filter(p=>{const order=orderMap.get(p.order_id);return (!status||p.status===status)&&(!product||order?.product_id===product)&&(!offer||order?.offer_id===offer)&&(!model||order?.settlement_model===model)&&(!method||methodOf(p)===method)&&(!period||new Date(p.created_at).getTime()>=cutoff);});
 const net=detail?.financial_snapshots?Number(detail.financial_snapshots.producer_amount_cents)-(detail.settlement_model==="prosperity_balance"?Number(chosen?.provider_fee_amount_cents??0):0):0;
 return <><PageHeader title="Pagamentos" description="Transações reais dos seus produtos."/>
 <section className="panel operational-panel"><div className="filter-row">
 <label>Período<select value={period} onChange={e=>{setPeriod(e.target.value);setCutoff(e.target.value?Date.now()-Number(e.target.value)*86400000:0);}}><option value="">Todos</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label>
 <label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{["pending","processing","approved","rejected","cancelled","refunded","charged_back"].map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Todos</option>{[...new Map(orders.map(o=>[o.product_id,o.products?.name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Oferta<select value={offer} onChange={e=>setOffer(e.target.value)}><option value="">Todas</option>{[...new Map(orders.filter(o=>!product||o.product_id===product).map(o=>[o.offer_id,o.offers?.name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Método<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Todos</option>{[...new Set(payments.map(methodOf).filter(m=>m!=="—"))].map(m=><option key={m}>{m}</option>)}</select></label>
 <label>Recebimento<select value={model} onChange={e=>setModel(e.target.value)}><option value="">Todos</option><option value="connected_account">Mercado Pago</option><option value="prosperity_balance">Saldo Prosperity</option></select></label></div>
 {list.length?list.map(p=><button type="button" className="record-row record-button" key={p.id} onClick={()=>setSelected(p.id)}><strong>{orderMap.get(p.order_id)?.products?.name??"Produto"}</strong><span>{formatCents(p.gross_amount_cents)} · {p.status}</span><span>{formatDate(p.created_at)} →</span></button>):<p>Nenhum pagamento encontrado.</p>}
 </section>{chosen&&detail&&<div className="detail-overlay" onClick={()=>setSelected(null)}><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="Detalhes do pagamento" onClick={e=>e.stopPropagation()}><button className="secondary-button" onClick={()=>setSelected(null)}>Fechar</button><h2>Pagamento</h2>{detail.customers&&<p>{detail.customers.name} · {detail.customers.email}</p>}<p>{detail.products?.name} · {detail.offers?.name}</p>
 <dl>{[["Bruto",formatCents(chosen.gross_amount_cents)],["Taxa gateway apurada",formatCents(chosen.provider_fee_amount_cents)],["Taxa Prosperity",formatCents(detail.financial_snapshots?.prosperity_fee_amount_cents)],["Afiliado",formatCents(detail.financial_snapshots?.affiliate_amount_cents)],["Coprodutor",formatCents(detail.financial_snapshots?.coproducer_amount_cents)],["Produtor após taxa apurada",formatCents(net)],["Método",methodOf(chosen)],["Modelo",detail.settlement_model],["Payment ID",chosen.external_payment_id??"Pendente"],["Referência",chosen.external_reference],["Status",chosen.status]].map(([key,value])=><div className="record-row" key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h3>Eventos</h3>{chosen.payment_transactions.length?chosen.payment_transactions.map((event,i)=><p key={i}>{formatDate(event.occurred_at??event.created_at)} · {event.transaction_type} · {event.status}</p>):<p>Aguardando eventos do processador.</p>}</aside></div>}</>;
}
