"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { formatCents,formatDate,requestJson } from "@/lib/operational";
type Balance={available_cents:number};type Pix={id:string;key_type:string;key_last4:string;status:string};type Identity={status:string};type Withdrawal={id:string;status:string;amount_cents:number;created_at:string};
export function WithdrawalsView(){const [balance,setBalance]=useState<Balance>({available_cents:0}),[pix,setPix]=useState<Pix[]>([]),[identity,setIdentity]=useState<Identity|null>(null),[items,setItems]=useState<Withdrawal[]>([]),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const [b,p,i,w]=await Promise.all([requestJson<{balance:Balance}>("/api/balance"),requestJson<{payoutAccounts:Pix[]}>("/api/financial-profile/pix"),requestJson<{verification:Identity|null}>("/api/financial-profile/identity"),requestJson<{withdrawals:Withdrawal[]}>("/api/withdrawals")]);setBalance(b.balance);setPix(p.payoutAccounts);setIdentity(i.verification);setItems(w.withdrawals);setError("");}catch(cause){setError(String(cause));}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),amountCents=Math.round(Number(d.get("amount"))*100);if(amountCents>balance.available_cents){setError("Valor acima do saldo disponível.");return;}if(!confirm(`Solicitar saque de ${formatCents(amountCents)}?`))return;try{await requestJson("/api/withdrawals",{method:"POST",body:JSON.stringify({amountCents,payoutAccountId:d.get("pix")})});setMessage("Saque solicitado.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Falha no saque.");}}
 const allowed=identity?.status==="approved"&&pix.some(item=>item.status==="verified");return <><PageHeader title="Saques" description="Solicite transferência do saldo disponível por Pix."/>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<section className="panel operational-panel"><h2>Disponível: {formatCents(balance.available_cents)}</h2>{!allowed?<p>Para sacar, conclua a verificação de identidade e cadastre uma chave Pix aprovada. <Link href="/conta">Dados financeiros →</Link></p>:<form onSubmit={submit} className="operational-form form-grid"><label>Chave Pix<select name="pix">{pix.filter(item=>item.status==="verified").map(item=><option key={item.id} value={item.id}>{item.key_type} · ••••{item.key_last4}</option>)}</select></label><label>Valor (R$)<input name="amount" type="number" min="0.01" max={balance.available_cents/100} step="0.01" required/></label><button className="primary-button" disabled={!balance.available_cents}>Solicitar saque</button></form>}</section><section className="panel operational-panel"><h2>Histórico</h2>{items.length?items.map(item=><div className="record-row" key={item.id}><strong>{formatCents(item.amount_cents)}</strong><span>{item.status}</span><span>{formatDate(item.created_at)}</span></div>):<p>Nenhum saque solicitado.</p>}</section></>}
